---
driver_plugin: vagrant

driver_config:
  require_chef_omnibus: true
  customize:
    cpus: 1
    memory: 512
  ssh:
    insert_key: false

provisioner:
  name: chef_zero
  always_update_cookbooks: true

platforms:
- name: centos-6.8
  run_list: ['recipe[yum-epel]']
  driver_config:
    box: bento/centos-6.8
- name: centos-7.2
  run_list: ['recipe[yum-epel]']
  driver_config:
    box: bento/centos-7.2
- name: ubuntu-14.04
  run_list: ['recipe[apt]']
  driver_config:
    box: bento/ubuntu-14.04
- name: ubuntu-16.04
  run_list: ['recipe[apt]']
  driver_config:
    box: bento/ubuntu-16.04

suites:
- name: default
  run_list:
  - recipe[rsc_tomcat::default]
  - recipe[rsc_tomcat::tags]
  attributes:
    cloud:
      provider: 'vagrant'
      public_ips: ['100.64.1.1']
      private_ips: ['10.0.2.15']
    rsc_ros:
      provider: AWS
      access_key: <%= ENV['AWS_ACCESS_KEY'] %>
      secret_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
      bucket: cdw-demo
      file: sample/sample.war
      destination: /opt/tomcat/webapps
      region: us-east-1
    rsc_tomcat:
      application_name: 'sample'
      listen_port: '8080'
      bind_network_interface: 'private'
      vhost_path: 'www.example.com'
      java:
        version: '8'
        flavor: 'oracle'
      database:
        provider:  'mysql'
        host: 'db1.example.com'
        user: 'app_user'
        password: 'app_pass'
        schema: 'app_test'
    rightscale:
      instance_uuid: '1111111'
